apiVersion: v1                 # Kubernetes API version
kind: PersistentVolume         # Kubernetes' resource kind we are creating
metadata:                      # Metadata of the resource kind we are creating
  name: mysql-pv
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"